apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Space
metadata:
  name: spring-dev-space
spec:
  availabilityTargets:
    - name: all-regions.tanzu.vmware.com
      replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      profiles:
        - name: networking.tanzu.vmware.com
          values:
            inline: null
        - name: spring-dev.tanzu.vmware.com
          values:
            inline: null
      resources: {}
  updateStrategy:
    type: RollingUpdate
