apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-crac-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"
