#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-world
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-world
spec:
  env:
  - name: APP_MESSAGE
    value: World
  - name: APP_VERSION
    value: #@ data.values.version
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: CRAC_FILES_DIR
    value: /var/crac/${APP_VERSION}/${NODE_NAME}
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  image: #@ data.values.registry_prefix+"/hello-world:"+data.values.arch+"-"+data.values.version
