apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-world
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-world
spec:
  env:
  - name: APP_MESSAGE
    value: World
  - name: CRAC_FILES_DIR
    value: /var/crac/cache
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  image: docker.io/springdeveloper/hello-world:amd64
  # source:
  #   git:
  #     url: https://github.com/trisberg/hello-world
  #     ref:
  #       branch: main
