#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello-world
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
        app.kubernetes.io/part-of: hello-world
    spec:
      containers:
      - image: #@ "docker.io/springdeveloper/hello-world:"+data.values.arch+"-"+data.values.version
        imagePullPolicy: IfNotPresent
        name: app
        env:
        - name: APP_VERSION
          value: #@ data.values.version
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CRAC_FILES_DIR
          value: /var/crac/${APP_VERSION}/${NODE_NAME}
        securityContext:
          capabilities:
            add:
            - CHECKPOINT_RESTORE
            - NET_ADMIN
            - SYS_PTRACE
          runAsUser: 0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        volumeMounts:
        - mountPath: /var/crac
          name: crac-cache
      volumes:
      - name: crac-cache
        persistentVolumeClaim:
          claimName: hello-world
