#@ load("@ytt:data", "data")
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
      - name: workload
        image: #@ "docker.io/springdeveloper/hello-world:"+data.values.arch+"-"+data.values.version
        imagePullPolicy: Always
        env:
        - name: REVISION_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['serving.knative.dev/revision']
        - name: REVISION_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['serving.knative.dev/revisionUID']
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CRAC_FILES_DIR
          value: /var/crac/${REVISION_NAME}/${REVISION_UID}/${NODE_NAME}
        securityContext:
          capabilities:
            add:
            - CHECKPOINT_RESTORE
            - SYS_ADMIN
            - SYS_PTRACE
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/crac
          name: crac-cache
      volumes:
      - name: crac-cache
        persistentVolumeClaim:
          claimName: hello-world