apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
      - name: workload
        image: docker.io/springdeveloper/hello-world:crac-job
        imagePullPolicy: Always
        env:
        - name: CRAC_FILES_DIR
          value: /var/crac/cache
        securityContext:
          capabilities:
            add:
            - CHECKPOINT_RESTORE
        volumeMounts:
        - mountPath: /var/crac
          name: crac-cache
      volumes:
      - name: crac-cache
        persistentVolumeClaim:
          claimName: hello-world-crac-cache
